#!/usr/bin/env python
# -*- coding: utf-8 -*-

import random
import string

tamanho = raw_input(
    "digite a quantidade de letras que você quer na sua senha:")
opcionais = raw_input("digite algum simbolo por preferencia:")

chars = string.letters + string.digits + opcionais
for x in xrange(10):
    senha = ""
    for x in xrange(int(tamanho)):
        senha += random.choice(chars)

    print senha
